#!/usr/bin/env bash

# Configures a new ubuntu machine by installing
# Nginx where it should be listening on port 80
# Serve a page that would return a Hello World string

sudo apt-get update -y
sudo apt-get install nginx -y

# starting inginx
sudo service nginx start

# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Creating new index
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html
