#!/usr/bin/env bash
# configures a new ubuntu machine by installing
# Nginx where it should be listening on port 80
# Serve a page that would return a Hello World string
#

#Updating and installing Nginx.
sudo apt-get update -y
sudo apt-get install nginx -y

#Setting up some minor stuff

# starting nginx service
sudo service nginx start

# allowing nginx on firewall
#sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
#cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
echo "Hello World!" | sudo tee /var/www/html/index.html

#performing a permanent redirection (301)
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Tochukwu92 permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# create a 404 custom error page
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_str="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = 404.html {\n\t\t\/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$new_str/" /etc/nginx/sites-enabled/default

# testing configuration for syntax error
sudo nginx -t

# Restarting nginx
sudo service nginx restart
