#!/usr/bin/env bash

# configuration of the firewall to accept only trafics from http, https and ssh

sudo apt-get update
sudo apt-get install ufw
sudo ufw enable
sudo ufw default deny incoming
sudo ufw defaulf allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw reload
